FROM python:3.11-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

WORKDIR /app

ENV UV_PROJECT_ENVIRONMENT=/usr/local

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev --no-install-project --group scraper
RUN patchright install chrome --with-deps

COPY tesco/tesco_api.py ./
COPY tesco/tesco_ids.py ./
COPY tesco/graphql_query.txt ./
COPY supervalu/supervalu_api.py ./
COPY aldi/aldi_api.py ./
COPY dunnes/dunnes_ids.py ./
COPY dunnes/dunnes_api.py ./

CMD ["python", "tesco_api.py"]
