version: 2

models:
  - name: stg_tesco
    columns:
      - name: tpnc
        tests:
          - unique
          - not_null

  - name: stg_aldi
    columns:
      - name: id
        tests:
          - unique
          - not_null